git clone https://github.com/Anomalous-Software/Android.Play.ExpansionLibrary.git %~dp0Android.Play.ExpansionLibrary
git clone https://github.com/Anomalous-Software/angle.git %~dp0angle-ms
hg clone https://threax@bitbucket.org/threax/bepuphysics %~dp0BEPUPhysics
git clone https://github.com/Anomalous-Software/bullet3.git %~dp0Bullet/src
hg clone https://threax@bitbucket.org/threax/dotnetzip %~dp0DotNetZip
hg clone https://threax@bitbucket.org/threax/freeimage.net %~dp0FreeImage.NET
hg clone https://threax@bitbucket.org/threax/irony %~dp0Irony
git clone https://github.com/Anomalous-Software/libRocket.git %~dp0libRocket/src
hg clone https://threax@bitbucket.org/threax/lucene.net %~dp0Lucene.net
git clone https://github.com/Anomalous-Software/ModernHttpClient.git %~dp0ModernHttpClient
hg clone https://threax@bitbucket.org/threax/mono.security %~dp0Mono/Mono.Security
hg clone https://threax@bitbucket.org/threax/msbuildextensions %~dp0MSBuild
git clone https://github.com/Anomalous-Software/mygui.git %~dp0MyGUI/Src
git clone https://github.com/Anomalous-Software/Newtonsoft.Json.git Newtonsoft.Json
hg clone https://threax@bitbucket.org/threax/oggvorbis %~dp0oggvorbis
hg clone https://threax@bitbucket.org/threax/ogre %~dp0Ogre/src
hg clone https://threax@bitbucket.org/threax/ogredeps %~dp0OgreDeps/src
git clone https://github.com/Anomalous-Software/OkHttp-Xamarin.git OkHttp-Xamarin
git clone https://github.com/Anomalous-Software/openal-soft.git %~dp0OpenALSoft/src
git clone https://github.com/Anomalous-Software/openal-soft-apportable.git %~dp0OpenALSoft/srcAndroid