git clone https://github.com/Anomalous-Software/Android.Play.ExpansionLibrary.git %~dp0Android.Play.ExpansionLibrary
git clone https://github.com/Anomalous-Software/angle.git %~dp0angle-ms
git clone https://github.com/Anomalous-Software/BEPUPhysics.git %~dp0BEPUPhysics
git clone https://github.com/Anomalous-Software/bullet3.git %~dp0Bullet/src
git clone https://github.com/Anomalous-Software/DotNetZip.git %~dp0DotNetZip
git clone https://github.com/Anomalous-Software/FreeImage.NET.git %~dp0FreeImage.NET
git clone https://github.com/Anomalous-Software/Irony.git %~dp0Irony
git clone https://github.com/Anomalous-Software/libRocket.git %~dp0libRocket/src
git clone https://github.com/Anomalous-Software/Lucene.NET.git %~dp0Lucene.net
git clone https://github.com/Anomalous-Software/ModernHttpClient.git %~dp0ModernHttpClient
git clone https://github.com/Anomalous-Software/Mono.Security.git %~dp0Mono/Mono.Security
git clone https://github.com/Anomalous-Software/MSBuildExtensions.git %~dp0MSBuild
git clone https://github.com/Anomalous-Software/mygui.git %~dp0MyGUI/Src
git clone https://github.com/Anomalous-Software/Newtonsoft.Json.git Newtonsoft.Json
git clone https://github.com/Anomalous-Software/oggvorbis.git %~dp0oggvorbis
hg clone https://threax@bitbucket.org/threax/ogre %~dp0Ogre/src
hg clone https://threax@bitbucket.org/threax/ogredeps %~dp0OgreDeps/src
git clone https://github.com/Anomalous-Software/OkHttp-Xamarin.git OkHttp-Xamarin
git clone https://github.com/Anomalous-Software/openal-soft.git %~dp0OpenALSoft/src
git clone https://github.com/Anomalous-Software/openal-soft-apportable.git %~dp0OpenALSoft/srcAndroid
git clone https://github.com/Anomalous-Software/OkHttpClient.git %~dp0OkHttpClient
git clone https://github.com/Anomalous-Software/square-bindings.git %~dp0square-bindings
git clone https://github.com/Anomalous-Software/square-bindings-externals.git %~dp0square-bindings/externals
git clone https://github.com/Anomalous-Software/openvr.git
