git clone https://github.com/AnomalousMedical/Android.Play.ExpansionLibrary.git %~dp0Android.Play.ExpansionLibrary
git clone https://github.com/AnomalousMedical/angle.git %~dp0angle-ms
git clone https://github.com/AnomalousMedical/BEPUPhysics.git %~dp0BEPUPhysics
git clone https://github.com/AnomalousMedical/bullet3.git %~dp0Bullet/src
git clone https://github.com/AnomalousMedical/DotNetZip.git %~dp0DotNetZip
git clone https://github.com/AnomalousMedical/FreeImage.NET.git %~dp0FreeImage.NET
git clone https://github.com/AnomalousMedical/Irony.git %~dp0Irony
git clone https://github.com/AnomalousMedical/libRocket.git %~dp0libRocket/src
git clone https://github.com/AnomalousMedical/Lucene.NET.git %~dp0Lucene.net
git clone https://github.com/AnomalousMedical/ModernHttpClient.git %~dp0ModernHttpClient
git clone https://github.com/AnomalousMedical/Mono.Security.git %~dp0Mono/Mono.Security
git clone https://github.com/AnomalousMedical/MSBuildExtensions.git %~dp0MSBuild
git clone https://github.com/AnomalousMedical/mygui.git %~dp0MyGUI/Src
git clone https://github.com/AnomalousMedical/Newtonsoft.Json.git Newtonsoft.Json
git clone https://github.com/AnomalousMedical/oggvorbis.git %~dp0oggvorbis
git clone --branch Anomalous https://github.com/AnomalousMedical/ogre.git %~dp0Ogre/src
git clone https://github.com/AnomalousMedical/OgreDeps.git %~dp0OgreDeps/src
git clone https://github.com/AnomalousMedical/OkHttp-Xamarin.git OkHttp-Xamarin
git clone https://github.com/AnomalousMedical/openal-soft.git %~dp0OpenALSoft/src
git clone https://github.com/AnomalousMedical/openal-soft-apportable.git %~dp0OpenALSoft/srcAndroid
git clone https://github.com/AnomalousMedical/OkHttpClient.git %~dp0OkHttpClient
git clone https://github.com/AnomalousMedical/square-bindings.git %~dp0square-bindings
git clone https://github.com/AnomalousMedical/square-bindings-externals.git %~dp0square-bindings/externals
git clone https://github.com/AnomalousMedical/openvr.git openvr
