#!/bin/sh

#Discover some stuff about where we are.
START_PATH=$(pwd)
THIS_FOLDER=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT_DEPENDENCY_FOLDER=$THIS_FOLDER/..

#Folders
SOURCE_FOLDER=$THIS_FOLDER/src
BUILD_FOLDER=$THIS_FOLDER/iOSBuild

    #Configuration
    GENERATOR_NAME=Xcode
    CMAKE_SETTINGS="-D OGRE_BUILD_COMPONENT_MESHLODGENERATOR=0 \
    -D OGRE_BUILD_COMPONENT_OVERLAY=0 \
    -D OGRE_BUILD_COMPONENT_PAGING=0 \
    -D OGRE_BUILD_COMPONENT_RTSHADERSYSTEM=0 \
    -D OGRE_BUILD_COMPONENT_TERRAIN=0 \
    -D OGRE_BUILD_COMPONENT_VOLUME=0 \
    -D OGRE_BUILD_PLUGIN_BSP=0 \
    -D OGRE_BUILD_PLUGIN_CG=0 \
    -D OGRE_BUILD_PLUGIN_OCTREE=0 \
    -D OGRE_BUILD_PLUGIN_PCZ=0 \
    -D OGRE_BUILD_PLUGIN_PFX=0 \
    -D OGRE_BUILD_RENDERSYSTEM_D3D9=0 \
    -D OGRE_BUILD_SAMPLES=0 \
    -D OGRE_BUILD_TOOLS=0 \
    -D OGRE_COPY_DEPENDENCIES=0 \
    -D OGRE_INSTALL_DEPENDENCIES=0 \
    -D OGRE_INSTALL_DOCS=0 \
    -D OGRE_INSTALL_PDB=0 \
    -D OGRE_INSTALL_SAMPLES=0 \
    -D OGRE_INSTALL_TOOLS=0 \
    -D CMAKE_INSTALL_PREFIX=$BUILD_FOLDER/Install \
    -D OGRE_BUILD_PLATFORM_APPLE_IOS=1 \
    -D OGRE_DEPENDENCIES_DIR=$ROOT_DEPENDENCY_FOLDER/OgreDeps/iOSInstall"

    #Make sure the build directories are empty by removing them
    rm -r "$BUILD_FOLDER"

    #Create the framework
    mkdir "$BUILD_FOLDER"
    cd "$BUILD_FOLDER"

    cmake -G "$GENERATOR_NAME" $CMAKE_SETTINGS $SOURCE_FOLDER

#Build with XCode
xcodebuild -configuration Release SHARED_PRECOMPS_DIR="$BUILD_FOLDER/SharedTmpPCH_device"

#Finish up
cd "$START_PATH"